# python_summary_part3

- Error handing
- Function


## Error handing
- syntax error
- runtime error
- logical errors

In [1]:
# syntax error - NameError: name 'prin' is not defined

prin("Linear regression is a supervised learning algorithm.")

# 线性回归是一种监督学习算法

NameError: name 'prin' is not defined

In [2]:
# runtime error -IndexError: list index out of range

numbers = list(range(5))
numbers

[0, 1, 2, 3, 4]

In [3]:
numbers[10]

IndexError: list index out of range

In [5]:
# logical errors - 是 r 的平方

import numpy as np

radius = 5
area_circle = np.pi*radius

# error: area = pi*radius**2
area_circle


15.707963267948966

### try-except


In [7]:
age = float(input("Give me your age."))
age

# ValueError: could not convert string to float: 'hello'

ValueError: could not convert string to float: 'hello'

In [8]:
# 不喜欢看见红色提醒，用try except 不报错但会出现提醒语句
try:
    age = float(input("Give me your age."))
except ValueError as err:
    print(err)

age

could not convert string to float: 'hello'


23.0

In [3]:
while True:
    try:
        age = float(input("Give me your age."))
        if not 0 <= age <= 125:
            raise ValueError("Year must be between 0 and 125")
        print(f"You are {age} years old.")
        break
    except ValueError as err:
        print(err)

        # 1.手动抛出 ValueError 异常。异常信息为 "Year must be between 0 and 125" ，自己定义的
        # 2.捕获异常：except ValueError as err 会捕获 try 块中抛出的 ValueError 异常。系统自动提示的

could not convert string to float: 'hello'
could not convert string to float: 'zoro'
Year must be between 0 and 125
You are 34.0 years old.


## Functions



A function is a reusable block of code that performs a specific task or a set of tasks

break down complex program into smaller parts
organize code
make modular code

def name(param1, param2, ...): 
    statements
    ...

name(arg1, arg2, ...)

In [6]:
# x is input parameter
def squarer(x):
    return x**2   # return statement

squarer(3)

9

In [8]:
squarers = [squarers(i) for i in range(10)]
squarers

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### default value

In [12]:
def draw_ascii(number_rows=5):
    for i in range(1, number_rows + 1):
        print(i * "x" + (number_rows - i) * "o")

draw_ascii()

xoooo
xxooo
xxxoo
xxxxo
xxxxx


In [13]:
draw_ascii(7)

xoooooo
xxooooo
xxxoooo
xxxxooo
xxxxxoo
xxxxxxo
xxxxxxx


In [14]:
draw_ascii(number_rows=3)

xoo
xxo
xxx


arbitrary arguments  任意参数  *args: tuple 元组形式储存

mean_， sum_ ：加下划线是防止区别于python 自带的mean，sum 函数，防止改写。
*args 是一个特殊的语法，用于接收可变数量的参数。它将传递给函数的所有位置参数打包成一个 元组，然后赋值给变量 args。
在这个例子中，args 将是一个元组。

In [16]:
def mean_(*args):
    sum_ = 0
    print(args)  # args is a tuple
    # for arg in args:

mean_(1, 2, 34)

(1, 2, 34)


In [21]:
def mean_(*args):
    sum_ = 0
    for arg in args:
        sum_ += arg
    return sum_/len(args)

mean_(1, 2, 34)

12.333333333333334

In [22]:
mean_(1, 2, 3)

2.0

keyword arguments *kwargs： 字典形式储存

*kwargs 是一种特殊的语法，用于接收不定数量的关键字参数（即以键值对的形式传递的参数）。
与 *args 接收位置参数不同，**kwargs 会将所有传递的关键字参数打包成一个 字典 (dictionary)。
np.random.randint 用于生成随机整数，size 参数定义了结果数组的形状。
size=(throws, dices)：
throws 是数组的行数，即有多少次掷骰子的记录。
dices 是数组的列数，即每次掷骰子时有多少颗骰子

In [27]:
import numpy as np

def simulate_dices(throws=1, dices=2):
    print(np.random.randint(1, 7, size=(throws, dices)))


# default argements
simulate_dices()

[[1 4]]


In [28]:
simulate_dices(10, 4)

[[1 5 6 3]
 [4 1 4 5]
 [5 4 4 4]
 [6 3 5 5]
 [3 4 5 4]
 [6 1 1 3]
 [5 4 5 5]
 [5 1 4 6]
 [5 3 1 4]
 [5 2 2 1]]


In [29]:
simulate_dices(throws=5)

[[4 1]
 [5 5]
 [6 5]
 [6 1]
 [6 2]]


In [30]:
simulate_dices(dices=3)

[[3 5 2]]


In [31]:
# do not need to follow the positions 
simulate_dices(dices=3, throws=5)

[[4 4 1]
 [2 5 1]
 [4 4 1]
 [3 1 6]
 [1 5 2]]


### unpacking 
在 Python 中，** 用于字典的解包（unpacking）。

一个 * 用于将多个位置参数收集成一个元组，列表 等。
两个 ** 用于将字典的键值对收集成函数的命名参数。

In [32]:
# unpacking 

options = {"dices":3, "throws":3}

simulate_dices(**options)

# 使用了 **options 语法来解包字典 options，将字典中的键值对作为命名参数传递给函数 simulate_dices。
# 等同于 simulate_dices(dices=3, throws=3)

[[3 5 2]
 [3 6 3]
 [4 5 4]]


In [33]:
option_list = [1, 5]

simulate_dices(*option_list)

[[2 2 6 3 4]]


### lambda functions

lambda functions: anonymous 匿名函数
do not need to create this function beforehand(事先的), instead I can use the anonymous function.

In [34]:
# def f(x):
#   return x**3  x power 3
f = lambda x: x**3 
f(3)

27

In [35]:
students = [("Bob", 92), ("Charlie", 78), ("David", 95), ("Alice", 85)]

students

[('Alice', 85), ('Bob', 92), ('Charlie', 78), ('David', 95)]

In [36]:
# sort 默认第一个，按名字排列 name
sorted(students)

[('Alice', 85), ('Bob', 92), ('Charlie', 78), ('David', 95)]

In [40]:
# 想按照成绩排序 score
sorted(students, key=lambda students: students[1])


[('Charlie', 78), ('Alice', 85), ('Bob', 92), ('David', 95)]

In [39]:
# reverse=True 倒转排序
sorted(students, key=lambda students: students[1], reverse=True)

[('David', 95), ('Bob', 92), ('Alice', 85), ('Charlie', 78)]